[package]
name = "npuzzle"
version = "0.1.0"
authors = ["pacifistes <bbrunell@student.42.fr>"]
edition = "2018"

[dependencies]
rand = "0.6.5"

[dev-dependencies]
criterion = "0.2"

# [[bench]]
# name = "my_benchmark"
# harness = false