[package]
name = "npuzzle"
version = "0.1.0"
authors = ["pacifistes <bbrunell@student.42.fr>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
libc = "0.2.48"

[lib]
name = "rust_lib"
crate-type = ["staticlib", "rlib"]